name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Inject OpenAI API Key
      run: |
        echo "Injecting OpenAI API Key into environment.prod.ts"
        sed -i 's/openaiApiKey: .*/openaiApiKey: \"${{ secrets.openaiApiKey }}\"/' src/environments/environment.prod.ts

    - name: Build Angular app
      run: |
        ng build --configuration production

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./dist/sabletech/browser  # Replace with your actual build directory

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './dist/sabletech/browser'
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 